steps:
- name: gcr.io/cloud-builders/bazel
  args: ['build', '--incompatible_use_python_toolchains', '//...:all']
- name: gcr.io/cloud-builders/bazel
  args: ['test', '--incompatible_use_python_toolchains', '//...:all']