steps:
- name: "docker.io/library/python:3.7"
  args: ['pip', 'install', 'pyserial']
- name: gcr.io/cloud-builders/bazel
  args: ['build', '--incompatible_use_python_toolchains', '//...:all']
- name: gcr.io/cloud-builders/bazel
  args: ['test', '--incompatible_use_python_toolchains',
         '--test_output=errors', '//...:all']