package(default_visibility = ["//visibility:public"])

py_library(
    name = "power_supply",
    srcs = ["power_supply.py"],
)

py_test(
    name = "power_supply_test",
    srcs = ["power_supply_test.py"],
    deps = [":power_supply"],
)
